# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\x12\x06kmeans\"Z\n\nMapRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x11\n\tcentroids\x18\x02 \x03(\x01\x12\x13\n\x0bindex_start\x18\x03 \x01(\x05\x12\x11\n\tindex_end\x18\x04 \x01(\x05\"/\n\x0bMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2D\n\rMapperService\x12\x33\n\x06RunMap\x12\x12.kmeans.MapRequest\x1a\x13.kmeans.MapResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=24
  _globals['_MAPREQUEST']._serialized_end=114
  _globals['_MAPRESPONSE']._serialized_start=116
  _globals['_MAPRESPONSE']._serialized_end=163
  _globals['_MAPPERSERVICE']._serialized_start=165
  _globals['_MAPPERSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
