# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\" \n\rNotifyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x10\n\x0eNotifyResponse23\n\x06Seller\x12)\n\x06Notify\x12\x0e.NotifyRequest\x1a\x0f.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYREQUEST']._serialized_start=16
  _globals['_NOTIFYREQUEST']._serialized_end=48
  _globals['_NOTIFYRESPONSE']._serialized_start=50
  _globals['_NOTIFYRESPONSE']._serialized_end=66
  _globals['_SELLER']._serialized_start=68
  _globals['_SELLER']._serialized_end=119
# @@protoc_insertion_point(module_scope)
