# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\x12\x05\x62uyer\" \n\rNotifyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0eNotifyResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.buyer.Status*\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32>\n\x05\x42uyer\x12\x35\n\x06Notify\x12\x14.buyer.NotifyRequest\x1a\x15.buyer.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=105
  _globals['_STATUS']._serialized_end=136
  _globals['_NOTIFYREQUEST']._serialized_start=22
  _globals['_NOTIFYREQUEST']._serialized_end=54
  _globals['_NOTIFYRESPONSE']._serialized_start=56
  _globals['_NOTIFYRESPONSE']._serialized_end=103
  _globals['_BUYER']._serialized_start=138
  _globals['_BUYER']._serialized_end=200
# @@protoc_insertion_point(module_scope)
