# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\x12\x06seller\" \n\rNotifyRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x0eNotifyResponse\x12\x1e\n\x06status\x18\x01 \x01(\x0e\x32\x0e.seller.Status*\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\x41\n\x06Seller\x12\x37\n\x06Notify\x12\x15.seller.NotifyRequest\x1a\x16.seller.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=108
  _globals['_STATUS']._serialized_end=139
  _globals['_NOTIFYREQUEST']._serialized_start=24
  _globals['_NOTIFYREQUEST']._serialized_end=56
  _globals['_NOTIFYRESPONSE']._serialized_start=58
  _globals['_NOTIFYRESPONSE']._serialized_end=106
  _globals['_SELLER']._serialized_start=141
  _globals['_SELLER']._serialized_end=206
# @@protoc_insertion_point(module_scope)
