# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raftNode_pb2 as raftNode__pb2


class RaftNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/raftNode.RaftNodeService/RequestVote',
                request_serializer=raftNode__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=raftNode__pb2.RequestVoteResponse.FromString,
                )
        self.AppendEntries = channel.unary_unary(
                '/raftNode.RaftNodeService/AppendEntries',
                request_serializer=raftNode__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=raftNode__pb2.AppendEntriesResponse.FromString,
                )
        self.ServeClient = channel.unary_unary(
                '/raftNode.RaftNodeService/ServeClient',
                request_serializer=raftNode__pb2.ServeClientArgs.SerializeToString,
                response_deserializer=raftNode__pb2.ServeClientResponse.FromString,
                )
        self.BroadcastMessage = channel.unary_unary(
                '/raftNode.RaftNodeService/BroadcastMessage',
                request_serializer=raftNode__pb2.BroadcastMessageRequest.SerializeToString,
                response_deserializer=raftNode__pb2.BroadcastMessageReply.FromString,
                )
        self.PeriodicTask = channel.unary_unary(
                '/raftNode.RaftNodeService/PeriodicTask',
                request_serializer=raftNode__pb2.PeriodicTaskRequest.SerializeToString,
                response_deserializer=raftNode__pb2.PeriodicTaskReply.FromString,
                )


class RaftNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeriodicTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=raftNode__pb2.RequestVoteRequest.FromString,
                    response_serializer=raftNode__pb2.RequestVoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=raftNode__pb2.AppendEntriesRequest.FromString,
                    response_serializer=raftNode__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'ServeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeClient,
                    request_deserializer=raftNode__pb2.ServeClientArgs.FromString,
                    response_serializer=raftNode__pb2.ServeClientResponse.SerializeToString,
            ),
            'BroadcastMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastMessage,
                    request_deserializer=raftNode__pb2.BroadcastMessageRequest.FromString,
                    response_serializer=raftNode__pb2.BroadcastMessageReply.SerializeToString,
            ),
            'PeriodicTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PeriodicTask,
                    request_deserializer=raftNode__pb2.PeriodicTaskRequest.FromString,
                    response_serializer=raftNode__pb2.PeriodicTaskReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raftNode.RaftNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftNode.RaftNodeService/RequestVote',
            raftNode__pb2.RequestVoteRequest.SerializeToString,
            raftNode__pb2.RequestVoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftNode.RaftNodeService/AppendEntries',
            raftNode__pb2.AppendEntriesRequest.SerializeToString,
            raftNode__pb2.AppendEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftNode.RaftNodeService/ServeClient',
            raftNode__pb2.ServeClientArgs.SerializeToString,
            raftNode__pb2.ServeClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BroadcastMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftNode.RaftNodeService/BroadcastMessage',
            raftNode__pb2.BroadcastMessageRequest.SerializeToString,
            raftNode__pb2.BroadcastMessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PeriodicTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raftNode.RaftNodeService/PeriodicTask',
            raftNode__pb2.PeriodicTaskRequest.SerializeToString,
            raftNode__pb2.PeriodicTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
